### ISSUE TITLE
🍊 Jupyter Notebook + 🕸 Replicate

### ISSUE THREAD

**Issue by camenduru** [TencentARC/InstantMesh#11]
Thanks for the project ❤️ I made a jupyter notebook and replicate demo 🥳 I hope you like it.  

https://github.com/camenduru/InstantMesh-jupyter
https://replicate.com/camenduru/instantmesh

**Comment by bluestyle97** [comment]
@camenduru Wow, we are so grateful for your contribution! We will add it into our README file.
