### ISSUE TITLE
Fine-Tuning Zero123++ pre-defined range of query image.

### ISSUE THREAD

**Issue by SBlumenstock1** [TencentARC/InstantMesh#114]
Hi, I try to finetune Zero123++ and in your paper you use a pre-defined range for the query image:

> "The azimuth, elevation and camera distance of the query image is randomly sampled from a pre-defined range." 

Can you explain in more detail what range you used for this?

**Comment by Mrguanglei** [comment]
@SBlumenstock1 Hello, have you used the dataset for training, please take a look at the configuration file of your dataset

**Comment by bluestyle97** [comment]
@SBlumenstock1 Sorry for the late reply. azimuth range: [0, 360], elevation range: [-20, 45], camera distance range: [2.5, 5.0]
