### ISSUE TITLE
 cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' 

### ISSUE THREAD

**Issue by stella0909** [TencentARC/InstantMesh#116]
当我使用： python app.py时。报错：mportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' 。

当我使用：python run.py configs/instant-mesh-large.yaml examples/ceshi.jpg 时依然报错：
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' 、

当我想直接  pip  install split_torch_state_dict_into_shards 这个模块的时候，
ERROR: Could not find a version that satisfies the requirement split_torch_state_dict_into_shards (from versions: none)
ERROR: No matching distribution found for split_torch_state_dict_into_shards、

啊我错在哪里了我不太明白，请教各位。

**Comment by ZhixianHuang** [comment]
pip install --upgrade huggingface_hub

**Comment by rooom13** [comment]
`pip install --upgrade huggingface_hub` did the job for me

**Comment by stella0909** [comment]
> pip install --upgrade huggingface_hub
非常感谢，对我来说是有帮助的，按照这个思路顺便upgrade了其他模块

**Comment by Blueyee** [comment]
work for me

**Comment by winniewlx** [comment]
I ran this command in the PyCharm terminal, but it still didn't solve the problem. Do I need to download pip in the C:\Users\30759\Desktop\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded directory and then run the command?Thanks.
