### ISSUE TITLE
Model3D.__init__() got an unexpected keyword argument 'width' when running app.py

### ISSUE THREAD

**Issue by schelmi1** [TencentARC/InstantMesh#12]
Hi, when starting **app.py** im getting the gradio error mentioned above.
Gradio version is 4.26.0

i resolved it by changing line 321 in app.py from
```width=768```
to 
```min_width=768```

**Comment by bluestyle97** [comment]
@schelmi1 Thanks for pointing this out. We have fixed this problem.
