### ISSUE TITLE
Where to place the fine-tuned weights?

### ISSUE THREAD

**Issue by asadullahnaeem** [TencentARC/InstantMesh#137]
I have trained the zero123++ model and I have a `.ckpt` file. From the pretrained weights there are only safetensor files. Do I need to convert this to safetensor and which model file needs to be replaced? Thanks in advance

**Comment by Maxbr2021** [comment]
you can just use the .ckpt file. However, in the run.py script you must assure that the file is compatible with torch.load. I used the following code:

```
state_dict = torch.load(unet_ckpt_path, map_location='cpu')

def lightning_to_torch(ckp):
    unet = {".".join(k.split(".")[2:]): v for k, v in ckp["state_dict"].items() if k.startswith("unet.unet.")}
    return unet

if load_unet_lightning:
    unet_pt = lightning_to_torch(state_dict)
    pipeline.unet.load_state_dict(unet_pt, strict=True)
else:
    pipeline.unet.load_state_dict(state_dict, strict=True)
```

**Comment by asadullah-adnare** [comment]
Yes, the issue was solved. Thanks for this code as well :)

**Comment by asadullahnaeem** [comment]
Yes, the weights had some extra keys and prefix of `unet.unet.`. After replacing these and placing the weights in unet folder solved the issue just did some keys manipulation in the safetensors directly. Btw thanks for this piece of code. :)
