### ISSUE TITLE
Mesh rendering script

### ISSUE THREAD

**Issue by MrTornado24** [TencentARC/InstantMesh#141]
Hi, Great work! Could you please upload the mesh rendering script corresponding to this figure in paper? Thanks a lot!
<img width="958" alt="image" src="https://github.com/user-attachments/assets/ffb29ad0-1591-4634-add9-60be9b542ce1">

**Comment by bluestyle97** [comment]
Please refer to [https://github.com/HTDerekLiu/BlenderToolbox](url).
