### ISSUE TITLE
Training on NeRF representation only returns white images for the rendered images and no depth maps.

### ISSUE THREAD

**Issue by SBlumenstock1** [TencentARC/InstantMesh#143]
I have tried to train on the NeRF representation, but the generator only returns white rendered images.

![train_0000250](https://github.com/user-attachments/assets/48596012-66ea-4a9e-8aa7-0a89e187d8b2)
![train_0001500](https://github.com/user-attachments/assets/a69a510c-3028-42a7-984e-39cd6796e21e)

Can someone please help me? Are the weights of the lrm_reconstructor not loaded correctly?

**Comment by Huangkangxian** [comment]
> Unfortunately, I don't have the answer to your question. However, since you have reached this step, I would like to ask if you could help me get there as well. How did you create your dataset? I managed to render a dataset with 32 random views, along with normal and depth maps. Now, I am stuck at the point where I have to save the camera positions for each view.

Hi, I would like to ask if you could help me render a dataset with 32 random views, along with normal and depth maps.Thanks a lot!

**Comment by bluestyle97** [comment]
@SBlumenstock1 If the model cannot render anything during the training process, there is most likely something wrong with the camera poses in your dataset. Please refer to [https://github.com/liuyuan-pal/SyncDreamer/blob/main/blender_script.py#L202](https://github.com/liuyuan-pal/SyncDreamer/blob/main/blender_script.py#L202) which used the same camera pose saving function as mine. To be noted, the function produces a **world2cam** matrix, please make sure it is inversed into a **cam2world** matrix in the dataloader.

**Comment by cjyryc** [comment]
I've encountered the same issue. I checked your processing in the dataset [https://github.com/TencentARC/InstantMesh/blob/main/src/data/objaverse.py#L186](https://github.com/TencentARC/InstantMesh/blob/main/src/data/objaverse.py#L186) and you've already converted the world-to-camera matrix to the camera-to-world matrix, so it shouldn't be that. I also refer to[https://github.com/liuyuan-pal/SyncDreamer/blob/main/blender_script.py](https://github.com/liuyuan-pal/SyncDreamer/blob/main/blender_script.py) for rendering the dataset , Could you please let me know where the problem might be?
![train_0000000](https://github.com/user-attachments/assets/973d9ddb-365a-4163-a57e-baf3af7e9161)

**Comment by SensenGao** [comment]
> I have tried to train on the NeRF representation, but the generator only returns white rendered images.
> 
> ![train_0000250](https://private-user-images.githubusercontent.com/166011324/359863692-48596012-66ea-4a9e-8aa7-0a89e187d8b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTIyNTksIm5iZiI6MTcyODgxMTk1OSwicGF0aCI6Ii8xNjYwMTEzMjQvMzU5ODYzNjkyLTQ4NTk2MDEyLTY2ZWEtNGE5ZS04YWE3LTBhODllMTg3ZDhiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwOTMyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDIzNTJlNzI3NjdjYTEzYWYxZGVhYzZiYjRkZWZkYzUwMmZmMTNhZWQxZmNhY2I2MmExZjg4MDkwMDAwMGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UFKKIUUpi1ixkiIOQwXHWwinonjIJ3rPNIecuXeynwU) ![train_0001500](https://private-user-images.githubusercontent.com/166011324/359863731-a69a510c-3028-42a7-984e-39cd6796e21e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTIyNTksIm5iZiI6MTcyODgxMTk1OSwicGF0aCI6Ii8xNjYwMTEzMjQvMzU5ODYzNzMxLWE2OWE1MTBjLTMwMjgtNDJhNy05ODRlLTM5Y2Q2Nzk2ZTIxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwOTMyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDJkZTI2M2I5NjIzMDk4MTYyZjQzYjY4ODQ2N2VjMDRkMDdmYWM0OTAyODhmMDdmMDkzNDFkOTg4N2Y1ZmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BN5IphcfCufxWRPhjK62BJXGmRhQS8LV4hYlJiYYTIg)
> 
> Can someone please help me? Are the weights of the lrm_reconstructor not loaded correctly?

I'm sorry to bother you. I used the camera pose data from the code along with the corresponding images, setting fx = fx * img_size, fy = fy * img_size, cx = 0.5 * img_size, and cy = 0.5 * img_size. Then, I trained a NeRF model using these parameters, but the training failed. The six images correspond to six separate 3D objects, with the result looking similar to the image below.
![79a884cf3736171086779c7dc0a928f](https://github.com/user-attachments/assets/e9a10ae3-fad5-4e8d-88c2-085f7f7151a2)

Could you provide details on the camera poses you have used?

**Comment by feiqiu-cyber** [comment]
> I've encountered the same issue. I checked your processing in the dataset https://github.com/TencentARC/InstantMesh/blob/main/src/data/objaverse.py#L186 and you've already converted the world-to-camera matrix to the camera-to-world matrix, so it shouldn't be that. I also refer tohttps://github.com/liuyuan-pal/SyncDreamer/blob/main/blender_script.py for rendering the dataset , Could you please let me know where the problem might be? ![train_0000000](https://private-user-images.githubusercontent.com/58896117/373644320-973d9ddb-365a-4163-a57e-baf3af7e9161.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDM1NjksIm5iZiI6MTczMjEwMzI2OSwicGF0aCI6Ii81ODg5NjExNy8zNzM2NDQzMjAtOTczZDlkZGItMzY1YS00MTYzLWE1N2UtYmFmM2FmN2U5MTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDExNDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyODE3ZjVjYzFiNzRjN2RhMDIyNDY1ZWYxYjgyZDJhMGNjMmJjNTUzMzBiNTNmZDgxOGE5ODI4YmMxNDY4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0DyaLQrdDfXvuSuOTYr50C33ItnrhlNubrqe62l_0_k) @bluestyle97 @SBlumenstock1 Thank you!

Have you solved the problem?  thank you

**Comment by cseconds** [comment]
> I have tried to train on the NeRF representation, but the generator only returns white rendered images.
> 
> ![train_0000250](https://private-user-images.githubusercontent.com/166011324/359863692-48596012-66ea-4a9e-8aa7-0a89e187d8b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NjkxNjksIm5iZiI6MTczMzY2ODg2OSwicGF0aCI6Ii8xNjYwMTEzMjQvMzU5ODYzNjkyLTQ4NTk2MDEyLTY2ZWEtNGE5ZS04YWE3LTBhODllMTg3ZDhiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxNDQxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2MwNmE2NmQzN2M2ZmI5ZjI1N2Q1YjExNzE4N2RlOTU3OTQ0ZjIzYTNkNWNkMTgxZTgyYzk3NjEwMzllZjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3QIv_7lTA1NGg07g10fPziRDRgvE5M2fhhLF0ghbzvU) ![train_0001500](https://private-user-images.githubusercontent.com/166011324/359863731-a69a510c-3028-42a7-984e-39cd6796e21e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NjkxNjksIm5iZiI6MTczMzY2ODg2OSwicGF0aCI6Ii8xNjYwMTEzMjQvMzU5ODYzNzMxLWE2OWE1MTBjLTMwMjgtNDJhNy05ODRlLTM5Y2Q2Nzk2ZTIxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxNDQxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmI5MmJiODM1ZGMwZTEzYjgxZGYxMGNjYTFkMGRkMzkzYjFlODk2OTlmOWQwMTg3OGVlNTUwYmM0ZWRmMmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.t7SOMvqYDmsdPVTRQzSwJV4nesmUhQOU1vEmZrT_8YM)
> 
> Can someone please help me? Are the weights of the lrm_reconstructor not loaded correctly?

I also encountered this problem. The pictures rendered by the model are all white. Have you found a solution?
