### ISSUE TITLE
The comparison of the number of input views (4 vs 6)

### ISSUE THREAD

**Issue by taeyeopl** [TencentARC/InstantMesh#162]
I saw the code using either 4 or 6 view results. Have you explored the difference? I wonder about the difference and which one is better. 

https://github.com/TencentARC/InstantMesh/blob/7fe95627cf819748f7830b2b278f302a9d798d17/run.py#L77

**Comment by bluestyle97** [comment]
Our model was trained on 6 input views. In practice, I didn't see notable differences using 4 or 6 views, since 4 views are usually enough to cover the whole object.

**Comment by taeyeopl** [comment]
Thanks :)
