### ISSUE TITLE
The rendered image does not match the original image

### ISSUE THREAD

**Issue by Dumeowmeow** [TencentARC/InstantMesh#166]
After I get the obj, I render it with camera parameters(0,0), the rendered image should normally be the same as the original image, but it fails, why?
The rendered image (azimuth:0,elevation:0):
![image](https://github.com/user-attachments/assets/f29bc022-1c51-4a73-b3d4-cdda45c64bf8)
The original image:
![image](https://github.com/user-attachments/assets/5aded1c9-940b-4c92-97fa-3c1d83be09c2)

**Comment by bluestyle97** [comment]
Zero123++ does not assume the input image's camera pose to be (0, 0). The azimuth of the input image is assume to be 0, but the elevation can be arbitrary and the model doesn't care aboout it since it generates images at fixed absolute elevations.
