### ISSUE TITLE
A serious bug of camera focal length

### ISSUE THREAD

**Issue by pupiljia** [TencentARC/InstantMesh#167]
In the file /InstantMesh/src/models/geometry/camera/perspective_camera.py, the calculation formula for focal length is incorrect。
![image](https://github.com/user-attachments/assets/d437f780-3b17-4d8f-b63b-56f16e499c3d)
And the correct one is:
![image](https://github.com/user-attachments/assets/e2d1e8b4-60fa-4642-8710-2811255f9cff)
I think the wrong focal length will make an incorrect projection matrix which is extremely important when rendering.  But I am not sure if it make a bad effect. 

And I have encountered a lot of confusion recently while writing my own render script to create a dataset. If someone is also attempt to retrain it , we can have a talk.

**Comment by bluestyle97** [comment]
This piece of code was directly borrowed from [Get3D](https://github.com/nv-tlabs/GET3D/blob/master/uni_rep/camera/perspective_camera.py#L28). I think the `focal` variable refers to `tan_half_fov` here, not the actual focal length.

**Comment by pupiljia** [comment]
> This piece of code was directly borrowed from [Get3D](https://github.com/nv-tlabs/GET3D/blob/master/uni_rep/camera/perspective_camera.py#L28). I think the `focal` variable refers to `tan_half_fov` here, not the actual focal length.

Oh，yes，you are right. `tan_half_fov ` will make a correct projection matrix。It's just a  name misunderstanding。
