### ISSUE TITLE
Pre-trained OpenLRM query

### ISSUE THREAD

**Issue by pupiljia** [TencentARC/InstantMesh#168]
I notice that Instantnerf reuse the pre-trained OpenLRM。But while I check the OpenLRM model, I find that there are some different  in model structure。
![image](https://github.com/user-attachments/assets/4114797a-bb35-409a-b80e-c1ea00f97836)
This one is most closed to Instantnerf config. But the resolution is different and it use dinov2 as the encoder model. 
I want to know: If you just load the weights from this github and model? If the different cause some bad effect?

**Comment by bluestyle97** [comment]
We used openlrm 1.0 instead of 1.1. You can checkout to their v1.0 branch and then will find the same model structure: https://github.com/3DTopia/OpenLRM/tree/v1.0.0

**Comment by pupiljia** [comment]
Thank you! But I still find a tiny different in the norm layer of  transformer model.
![image](https://github.com/user-attachments/assets/42e65349-8e80-405c-8666-94e196bdaebc)
And I find that it is just a norm layer  in V1.1.0. But I find that the dataset in huggingface only have  v1.0 and v1.1。Maybe I need to modify this part。 ：(

**Comment by pupiljia** [comment]
Thank you.But there is still a small different in transformer model's norm layer because the OpenLRM use the ModLN.
