### ISSUE TITLE
cached_download no longer exists on hugging face

### ISSUE THREAD

**Issue by jacksonkr** [TencentARC/InstantMesh#169]
```
$ python run.py configs/instant-mesh-large.yaml examples/hatsune_miku.png --save_video --no_rembg
Traceback (most recent call last):
  File "/mnt/c/Users/Jackson/Documents/git/InstantMesh/run.py", line 13, in <module>
    from diffusers import DiffusionPipeline, EulerAncestralDiscreteScheduler
  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 34, in <module>
    from .utils import (
  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 37, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/jackson/.local/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/jackson/.local/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```

I ran into the same issue with another repo. Apparently cached_download was removed in hugginface 0.26 as per https://github.com/huggingface/huggingface_hub/issues/2617

**Comment by ciscogeek** [comment]
same issue

**Comment by Aplegas** [comment]
Hi, everyone just locate the "cached_download" import in the module "dynamic_modules_utils.py" and remove it.
I think it was left there by mistake because it was imported by never used.
Also you might need to install the following:
`pip install "jax[cuda12_local]==0.4.23" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`
according to:
[stackoverflow](https://stackoverflow.com/questions/78302031/stable-diffusion-attributeerror-module-jax-random-has-no-attribute-keyarray
).

**Comment by LukeLIN-web** [comment]
refer https://github.com/huggingface/diffusers/blob/dac623b59f52c58383a39207d5147aa34e0047cd/examples/community/README.md?plain=1#L13 
remove it .

**Comment by jacksonkr** [comment]
I'm not exactly sure what fixed this for me but here's what I'm on now:

python3 --version >> 3.12.3
torch.__version__ >> 2.5.1+cu121
huggingface_cli env >> huggingface_hub version: 0.23.0

it seems like `sudo apt install nvidia-cuda-toolkit` played a role. Also I was working in wsl1 before and now I'm on wsl2. I still can't get the app.py to work via wsl but the command line img to video works fine eg.  `python run.py configs/instant-mesh-large.yaml examples/hatsune_miku.png --save_video`
