### ISSUE TITLE
zero123++v1.1

### ISSUE THREAD

**Issue by Dumeowmeow** [TencentARC/InstantMesh#173]
Hi!Can I use zero123++v1.1's output as the input of this method?Do I need to finetune?

**Comment by bluestyle97** [comment]
Yes you can. The simplest method is to use rembg to remove the gray background of the generated images.

**Comment by Dumeowmeow** [comment]
> Yes you can. The simplest method is to use rembg to remove the gray background of the generated images.

Does this mean that instantmesh supports both zero123++v1.1 and v1.2?
