### ISSUE TITLE
2020 m1 macbook pro weird errors everywhere

### ISSUE THREAD

**Issue by covalspace** [TencentARC/InstantMesh#2]
(instantmesh) me@myshit InstantMesh-main % python run.py configs/instant-mesh-large.yaml examples/hatsune_miku.png --save_video --no_rembg
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
/Users/me/opt/anaconda3/envs/instantmesh/lib/python3.10/site-packages/transformers/utils/generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Seed set to 42
Loading diffusion model ...
Loading pipeline components...:  25%|████████████████████████▊                                                                          | 2/8 [00:00<00:01,  5.49it/s]The config attributes {'dropout': 0.0, 'reverse_transformer_layers_per_block': None} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:06<00:00,  1.27it/s]
Loading custom white-background unet ...
Traceback (most recent call last):
  File "/Users/me/Desktop/InstantMesh-main/run.py", line 109, in <module>
    state_dict = torch.load(infer_config.unet_path, map_location='cpu')
  File "/Users/me/opt/anaconda3/envs/instantmesh/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/me/opt/anaconda3/envs/instantmesh/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/me/opt/anaconda3/envs/instantmesh/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/diffusion_pytorch_model.bin'

**Comment by bluestyle97** [comment]
@covalspace Hi, please download the model checkpoints from the [model card](https://huggingface.co/TencentARC/InstantMesh) first and put them under the `ckpts` folder.

**Comment by covalspace** [comment]
Hi sorry I don't know what any of this means. I downloaded the zip extracted and followed the readme. I don't have a ckpts folder and don't know what checkpoints are. I'm assuming these are the model checkpoints?

[instant_mesh_base.ckpt](https://huggingface.co/TencentARC/InstantMesh/blob/main/instant_mesh_base.ckpt)
1.25 GB
LFS
[upload](https://huggingface.co/TencentARC/InstantMesh/commit/478476440a2fcd64a2db9fcddc7a358fa443b295)
[1 day ago](https://huggingface.co/TencentARC/InstantMesh/commit/478476440a2fcd64a2db9fcddc7a358fa443b295)
[instant_mesh_large.ckpt](https://huggingface.co/TencentARC/InstantMesh/blob/main/instant_mesh_large.ckpt)
1.51 GB
LFS
[upload](https://huggingface.co/TencentARC/InstantMesh/commit/478476440a2fcd64a2db9fcddc7a358fa443b295)
[1 day ago](https://huggingface.co/TencentARC/InstantMesh/commit/478476440a2fcd64a2db9fcddc7a358fa443b295)
[instant_nerf_base.ckpt](https://huggingface.co/TencentARC/InstantMesh/blob/main/instant_nerf_base.ckpt)
1.25 GB
LFS
[upload](https://huggingface.co/TencentARC/InstantMesh/commit/478476440a2fcd64a2db9fcddc7a358fa443b295)
[1 day ago](https://huggingface.co/TencentARC/InstantMesh/commit/478476440a2fcd64a2db9fcddc7a358fa443b295)
[instant_nerf_large.ckpt](https://huggingface.co/TencentARC/InstantMesh/blob/main/instant_nerf_large.ckpt)
1.51 GB
LFS
[upload](https://huggingface.co/TencentARC/InstantMesh/commit/478476440a2fcd64a2db9fcddc7a358fa443b295)
[1 day ago](https://huggingface.co/TencentARC/InstantMesh/commit/478476440a2fcd64a2db9fcddc7a358fa443b295)

where should the ckpts folder be?

**Comment by bluestyle97** [comment]
@covalspace The `ckpts` folder should be under the source directory of this project,, i.e., `/path/to/InstantMesh/ckpts/`, please create it yourself. After downloading the reconstruction model and the diffusion unet, their model paths should be `/path/to/InstantMesh/ckpts/instant_mesh_large.ckpt` and `/path/to/InstantMesh/ckpts/diffusion_pytorch_model.bin`.  
By the way, `run.py` can download the required models automatically now. You can pull the newest code so that you don't need to care about the model path anymore.

**Comment by covalspace** [comment]
AssertionError: Torch not compiled with CUDA enabled

idk what the issue is I was able to run tripoSR so  idk

**Comment by covalspace** [comment]
this issue is not complete

**Comment by HaFred** [comment]
TripoSR supports torch-cpu, that's probably why you can run it with a MacBook but not for this one...
