### ISSUE TITLE
最低需要多少显存？24G能跑得了吗？

### ISSUE THREAD

**Issue by ChenHuiLang** [TencentARC/InstantMesh#20]
我用24G的显存，报错了，是不是显存不够？

**Comment by ChenHuiLang** [comment]
我用命令行的方式调用instant-mesh-large模型显存就够用了，用app.py可视化的那个估计是加载了多个模型导致显存不够，问题解决了

**Comment by sp1cae** [comment]
> 我用命令行的方式调用instant-mesh-large模型显存就够用了，用app.py可视化的那个估计是加载了多个模型导致显存不足，问题解决了

python run.py configs/instant-mesh-large.yaml examples/hatsune_miku.png --save_video 这个命令吗， 3090还是会显存不够

**Comment by ChenHuiLang** [comment]
我主要是想要生成3d模型，没有生成视频，而且图片本身就已经去了背景，我也是用3090，显存够，命令如下：
python run.py configs/instant-mesh-large.yaml examples/hatsune_miku.png --no_rembg --export_texmap

> > 我用命令行的方式调用instant-mesh-large模型显存就够用了，用app.py可视化的那个估计是加载了多个模型导致显存不足，问题解决了
> 
> python run.py configs/instant-mesh-large.yaml examples/hatsune_miku.png --save_video 这个命令吗， 3090还是会显存不够

**Comment by sp1cae** [comment]
> 我主要是想要生成3d模型，没有生成视频，而且图片本身就已经去了背景，我也是用3090，显存够了，命令如下： python run.py configs/instant-mesh-large.yaml Examples/hatsune_miku. png --no_rembg --export_texmap
> 
> > > 我用命令行的方式调用instant-mesh-large模型显存就够用了，用app.py可视化的那个估计是加载了多个模型导致显存不足，问题解决了
> > 
> > 
> > python run.py configs/instant-mesh-large.yaml Examples/hatsune_miku.png --save_video这个命令吗， 3090还是会显存不够

解决了谢谢~

**Comment by bluestyle97** [comment]
@kingnobro 这个应该是因为nerf的volume rendering比较占显存，试试不保存video呢（把`--save_video`去掉）？

**Comment by kingnobro** [comment]
@bluestyle97 可以了 :)
