### ISSUE TITLE
Running on a LAN of multiple GPUs

### ISSUE THREAD

**Issue by jazelly** [TencentARC/InstantMesh#24]
Hi, this is truly amazing work! 

We'd like to run it on a LAN of multiple servers, which have 8 -24gm vram unevenly. Is it possible to run this model on multiple GPUs? It looks like most people are running it on 24gb vram as a bare minimum

Thanks

**Comment by JustinPack** [comment]
@jazelly This would be a significant rewrite of the current application and the corresponding setup of your server and network environment would also require special attention. There would be other roadblocks to this working well but the previous two issues would be the largest you would have to overcome for starters.

**Comment by jazelly** [comment]
@JustinPack Thanks. That makes sense. We can wait for the small size gpu support
