### ISSUE TITLE
一直卡着，直到报错。。。

### ISSUE THREAD

**Issue by mikestut** [TencentARC/InstantMesh#31]
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sudo-ai/zero123plus-v1.2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa9a8358210>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: ae9ede8d-b9e4-4530-bc6a-7e259b76257e)')

**Comment by jtydhr88** [comment]
你本地网络连不上huggingface

**Comment by bluestyle97** [comment]
这是你网络的问题，请自己解决。
