### ISSUE TITLE
 Questions about absolute elevations

### ISSUE THREAD

**Issue by glorioushonor** [TencentARC/InstantMesh#33]
GOOD JOB! Why change the absolute elevations of 30° and -20° in zero123++ to absolute elevations of 20° and -10°?"

**Comment by bluestyle97** [comment]
Zero123++ v1.2 changed the fixed elevations from 30° and -20° to 20° and -10°. You can refer to their [official repo](https://github.com/SUDO-AI-3D/zero123plus?tab=readme-ov-file#updates-v12) for more details.
