### ISSUE TITLE
Fail to run the code on my local GPUs due to PyTorch and CUDA version.

### ISSUE THREAD

**Issue by snowflakewang** [TencentARC/InstantMesh#38]
Hello, thank you for your brilliant work on feed-forward-style Image-to-3D generation! I have tried your work on the HuggingFace demo and it works well!
I want to run your code on my local GPUs. However, due to some inevitable problems, my GPUs do not support the newest 12.x CUDA version and cannot be updated. So do you have any methods to run the code based on PyTorch 1.1x (such as 1.12, 1.13) and CUDA 11.x (such as 11.4, 11.6)?

Thanks a lot! :)

**Comment by bluestyle97** [comment]
I'm sorry but we haven't tested on older pytorch or CUDA versions. It seems that using older pytorch version (<= 2.0) may lead to errors in the attention operation #8. However, pytorch 2.1+ is indeed compatible with CUDA 11.x, the pytorch offical site has provided the command for installing the newest pytorch with CUDA 11.x.

**Comment by bluestyle97** [comment]
@joshkiller We did not make a thorough test but I don't think 8GB is enough.
