### ISSUE TITLE
Questions on loss

### ISSUE THREAD

**Issue by LaFeuilleMorte** [TencentARC/InstantMesh#44]
Hi, thanks for the great work. I've  read the code. And found that the depth loss was calculated, yet not sum into the total loss. Is there any reasons for doing so? 
![image](https://github.com/TencentARC/InstantMesh/assets/43473814/0ce55564-d293-4234-b50f-d96882b3ade7)

**Comment by bluestyle97** [comment]
It's indeed a typo. Thanks for pointing this out.
