### ISSUE TITLE
connectRrror，怎么去解决，科学上网也不可以呢

### ISSUE THREAD

**Issue by Mrguanglei** [TencentARC/InstantMesh#49]
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sudo-ai/zero123
plus-v1.2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbaceffa620>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: ca57e223-bc50-41fd-be5a-67ccfba32a47)')

**Comment by bluestyle97** [comment]
网络问题请自己解决，我们无能为力。

**Comment by huohuochenchen** [comment]
![1](https://github.com/TencentARC/InstantMesh/assets/168953327/435b4149-ba2d-4a8b-9708-af6442c4925d)
