### ISSUE TITLE
如何配置双卡GPU?

### ISSUE THREAD

**Issue by TzyTman** [TencentARC/InstantMesh#53]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB. GPU 0 has a total capacty of 23.69 GiB of which 368.94 MiB is free. Including non-PyTorch memory, this process has 23.33 GiB memory in use. Of the allocated memory 22.72 GiB is allocated by PyTorch, and 287.94 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by bluestyle97** [comment]
Hi, we have add two-GPU support for the demo app. Please checkout the newest code and README.

**Comment by TzyTman** [comment]
> 您好，我们为演示应用程序添加了两个 GPU 支持。请查看最新的代码和 README。

Thank you very much for having solved the dual GPU perfectly!
