### ISSUE TITLE
Fewer and greater numbers of view

### ISSUE THREAD

**Issue by reynoldscem** [TencentARC/InstantMesh#59]
Hi,

Do you have any results using fewer or more images? In the paper you mention this being possible. Tangentially, can arbitrary viewpoints be used for the conditioning images or must they match the distribution used in training?

**Comment by bluestyle97** [comment]
As demonstrated in the paper, we use free-viewpoint images during training. So yes. arbitrary viewpoints can be used for the conditioning images.

**Comment by reynoldscem** [comment]
That's great, thank you.
