### ISSUE TITLE
ComfyUI support

### ISSUE THREAD

**Issue by jtydhr88** [TencentARC/InstantMesh#6]
I implemented ComfyUI support for this, https://github.com/jtydhr88/ComfyUI-InstantMesh

**Comment by bluestyle97** [comment]
@jtydhr88 Wow, thanks for your contribution!

**Comment by bluestyle97** [comment]
@jtydhr88 We have add the ComfyUI support to our README file. Thanks for your contribution again!

**Comment by jtydhr88** [comment]
cool!
