### ISSUE TITLE
找不到本地模型文件，app.py一直停留在加载中

### ISSUE THREAD

**Issue by fingermelody** [TencentARC/InstantMesh#68]
下载模型文件到本地根目录下的ckpts文件，断开互联网，执行app.py 一直停留在加载模型中，是需要其他配置读取本地目录吗？

工程目录文件及执行命令如下：
---------------------------------------------------------------------------------------------------------------------------

root@acr6-6b4ff7db6c-bzb74:/InstantMesh# ls
LICENSE  README.md  app.py  assets  ckpts  configs  examples  requirements.txt  run.py  src  train.py  zero123plus
root@acr6-6b4ff7db6c-bzb74:/InstantMesh# cd ckpts
root@acr6-6b4ff7db6c-bzb74:/InstantMesh/ckpts# ls
diffusion_pytorch_model.bin  instant_mesh_base.ckpt  instant_mesh_large.ckpt  instant_nerf_base.ckpt  instant_nerf_large.ckpt
root@acr6-6b4ff7db6c-bzb74:/InstantMesh/ckpts# cd ..
root@acr6-6b4ff7db6c-bzb74:/InstantMesh# python app.py
Seed set to 0
Loading diffusion model ...

**Comment by bluestyle97** [comment]
应该不能断开互联网。我们的diffusion model权重只包含了unet，vae和clip的权重还是需要从huggingface上下载的。

**Comment by fingermelody** [comment]
那unet会默认找本地ckpts文件夹里的文件吗

Jiale Xu ***@***.***> 于2024年5月7日周二 15:06写道：

**Comment by bluestyle97** [comment]
会的
