### ISSUE TITLE
Question about the input_view_num in instant-mesh-large-train.yaml

### ISSUE THREAD

**Issue by wenqsun** [TencentARC/InstantMesh#7]
Thanks for your great work!

I think that in the config file instant-mesh-large-train.yaml
https://github.com/TencentARC/InstantMesh/blob/5e98c1436b71a008c69e3f07dd4b4ab66c294048/configs/instant-mesh-large-train.yaml#L38   the input_view_num should be 6?

I am looking forward to your reply! Thanks!

**Comment by bluestyle97** [comment]
@wenqsun Yes, it's a typo. When I test the training code, I reduce the input view num to save momory. Thanks for pointing this out!

**Comment by wenqsun** [comment]
Thanks for your kind reply!
