### ISSUE TITLE
Some weights of ViTModel were not initialized from the model checkpoint at facebook/dino-vitb16

### ISSUE THREAD

**Issue by JINNMnm** [TencentARC/InstantMesh#70]
When I try to use the training code to overfit one object to test the model and I encounter this:
```
Some weights of ViTModel were not initialized from the model checkpoint at facebook/dino-vitb16 and are newly initialized: ['encoder.layer.3.adaLN_modulation.1.bias', 'encoder.layer.1.adaLN_modulation.1.bias', 
'encoder.layer.1.adaLN_modulation.1.weight', 'encoder.layer.4.adaLN_modulation.1.weight', 
'encoder.layer.11.adaLN_modulation.1.bias', 'encoder.layer.8.adaLN_modulation.1.bias', 'encoder.layer.7.adaLN_modulation.1.bias', 
'encoder.layer.5.adaLN_modulation.1.weight', 'encoder.layer.6.adaLN_modulation.1.weight', 
'encoder.layer.4.adaLN_modulation.1.bias', 'encoder.layer.2.adaLN_modulation.1.bias', 'encoder.layer.0.adaLN_modulation.1.bias', 
'encoder.layer.10.adaLN_modulation.1.weight', 'encoder.layer.0.adaLN_modulation.1.weight', 
'encoder.layer.11.adaLN_modulation.1.weight', 'encoder.layer.9.adaLN_modulation.1.bias', 
'encoder.layer.9.adaLN_modulation.1.weight', 'encoder.layer.7.adaLN_modulation.1.weight', 
'encoder.layer.10.adaLN_modulation.1.bias', 'encoder.layer.6.adaLN_modulation.1.bias', 'encoder.layer.5.adaLN_modulation.1.bias', 
'encoder.layer.2.adaLN_modulation.1.weight', 'encoder.layer.3.adaLN_modulation.1.weight', 
'encoder.layer.8.adaLN_modulation.1.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```
It seems that the ViTModel is slightly modified?
I'm wondering if I just use the pretrained weight, can I successfully overfit an object?

**Comment by bluestyle97** [comment]
We add AdaLN modulation layers into the original dino model to inject camera poses. This warning is from the transformers package and will not influence the model's performance, since our pretrained weights contain these parameters and can be loaded properly.

**Comment by JINNMnm** [comment]
Thanks for your reply!
If I want to train it myself, can I just ignore this warning? Or should I load the pretrained weights, but it seems that the pretrained weight for the modified ViTModel isn't published?
Thanks again for your work!

**Comment by JINNMnm** [comment]
> We add AdaLN modulation layers into the original dino model to inject camera poses. This warning is from the transformers package and will not influence the model's performance, since our pretrained weights contain these parameters and can be loaded properly.

Thanks for your reply!
If I want to train it myself, can I just ignore this warning? Or should I load the pretrained weights, but it seems that the pretrained weight for the modified ViTModel isn't published?
Thanks again for your work!

**Comment by bluestyle97** [comment]
As I have stated, all the weights of the modified ViT encoder are just in the ckpt file. How can our model even work without these weights? The `transformers` package gives this warning bacause the pretrained DINO does not contain the weights of AdaLN modulation layers, but our pretrained ViT encoder does.

**Comment by HaFred** [comment]
> As I have stated, all the weights of the modified ViT encoder are just in the ckpt file. The `transformers` package gives this warning bacause the pretrained DINO does not contain the weights of AdaLN modulation layers, but our pretrained ViT encoder does.

Hi, may I know how did you load the openlrm weights for your training of instantnerf? Is it like matching the openlrm keys to instantnerf model keys mannually? There are literally 300+ kv pairs to match...
