### ISSUE TITLE
subprocess.py 526 run raise CalledProcessError(retcode, process.args,  subprocess.CalledProcessError: 1 ['which', 'c++']

### ISSUE THREAD

**Issue by Deadavid2012** [TencentARC/InstantMesh#76]
Hello, firts of all, thanks for creating this amazing project! There is an error when i try to run the app.py in my local machine

subprocess.py 526 run
raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError:
1
['which', 'c++']

I have succesfully installed all requirements and I have just checked all again before publishing this issue.

Im running the app in a virtual environment as suggested, with the following specs:

WSL (Ubuntu) inside Windows 11
CPU: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics        3.80 GHz (ARM64)
GPU: NVIDIA RTX4060 (8Gb)
RAM: 32Gb

I launched the run.py, and it seemed it worked without errors, but after the generation there was no archive generated. I tried it with the Miku example. But today I have tried again and I get the same error as with the app.py .

Thanks in advance.

**Comment by Deadavid2012** [comment]
I can't delete this issue, but today I tried again without doing anything different and it worked. Sorry for the onconvenience,

**Comment by liuhao16** [comment]
I had the same problem. It's always been the same，Nothing is being operated
，that's strange
