### ISSUE TITLE
8GB of models downloading every time I launch app.py

### ISSUE THREAD

**Issue by knuthnads** [TencentARC/InstantMesh#95]
Every time I run app.py it needs to redownload all 8GBs of models. Could it not just reuse the models it already downloaded?

I've tried manually downloading diffusion_pytorch_model.bin, instant_mesh_base.ckpt, instant_mesh_large.ckpt, instant_nerf_base.ckpt and instant_nerf_large.ckpt and copied them to the ckpts folder, but it seems like they're being disregarded entirely.

**Comment by stedf** [comment]
Did you solve it ? I have the same issue...
